// Mocks generated by Mockito 5.2.0 from annotations
// in sclp_final/test/repo/repo_auth_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sclp_final/repo/repo_auth.dart' as _i2;

import 'repo_auth_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResultRepoAuth_0 extends _i1.Fake implements _i2.ResultRepoAuth {}

/// A class which mocks [FakeRepoAuth].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeRepoAuth extends _i1.Mock implements _i3.FakeRepoAuth {
  MockFakeRepoAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ResultRepoAuth> authorize(
          String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#authorize, [username, password]),
              returnValue:
                  Future<_i2.ResultRepoAuth>.value(_FakeResultRepoAuth_0()))
          as _i4.Future<_i2.ResultRepoAuth>);
}
